name: macros-manager-testing
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout-repo
      uses: actions/checkout@v3
    
    - name: setup-node
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: frontend-dependency-installing
      run: |
        cd frontend
        npm i
    - name: frontend-testing
      run: |
        cd frontend
        npm test
    